const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
async function sample(page){await page.goto('/editor.html');await page.getByRole('button',{name:'Try The Description',exact:true}).click();await expect(page.locator('#workspace')).toBeVisible();}
async function exported(page){const event=page.waitForEvent('download');await page.getByRole('button',{name:'Export project',exact:true}).click();return JSON.parse(await fs.readFile(await(await event).path(),'utf8'));}
test('phone editor preserves recordings, invalidates edited speech, and exports a round trip',async({page})=>{
 await page.setViewportSize({width:390,height:844});await sample(page);const before=await exported(page);expect(Object.keys(before.assets.audio)).toHaveLength(8);expect(Buffer.from(before.assets.sprites['description-burglar-front'].split(',')[1],'base64').toString()).toContain('id="body"');
 await page.locator('.beat').filter({hasText:'1.2 seconds'}).first().click();await page.getByLabel('Pause (seconds)').fill('0.8');await page.getByRole('button',{name:'Save pause',exact:true}).click();expect((await exported(page)).assets.audio).toEqual(before.assets.audio);
 await page.locator('.beat').filter({hasText:'Suspect is a pelican'}).click();await page.getByLabel('Dialogue',{exact:true}).fill('Suspect appears to be a very suspicious pelican.');await page.getByRole('button',{name:'Save line',exact:true}).click();await expect(page.locator('#voice-status')).toContainText('1 line needs');const changed=await exported(page);expect(changed.assets.audio['line-0']).toBeUndefined();expect(changed.assets.audio['line-1']).toBe(before.assets.audio['line-1']);
 await page.reload();await expect(page.locator('#voice-status')).toContainText('1 line needs');expect((await exported(page)).assets.audio['line-0']).toBeUndefined();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 await page.locator('#project-file').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(changed))});await expect(page.locator('#project-title')).toHaveValue(before.meta.title);expect((await exported(page)).assets.audio).toEqual(changed.assets.audio);
});
test('character edits, undo, and contextual copy work without an agent connection',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await sample(page);await page.locator('#cast-list').getByRole('button',{name:'burglar',exact:true}).click();await page.getByLabel('Across (%)').fill('40');await page.getByRole('button',{name:'Update position'}).click();expect((await exported(page)).cast.burglar.x).toBe(40);await page.getByRole('button',{name:'Undo',exact:true}).click();expect((await exported(page)).cast.burglar.x).toBe(68);
 await page.getByLabel('A note for your agent').fill('Give this pelican a tiny crown.');await page.getByRole('button',{name:'Copy request for your agent'}).click();const request=await page.evaluate(()=>navigator.clipboard.readText());expect(request).toContain('tiny crown');expect(request).toContain('"id": "burglar"');expect(request).not.toContain('data:audio');
 await page.locator('#play').click();await expect(page.locator('#preview')).toHaveAttribute('src',/recordedOnly=1/);await expect(page.frameLocator('#preview').locator('#playBtn')).toBeEnabled();await page.frameLocator('#preview').locator('#playBtn').click();await expect(page.frameLocator('#preview').locator('body')).toHaveAttribute('data-playback-state','playing');await page.getByRole('button',{name:'Back to editing'}).click();await expect(page.locator('#layout-stage')).toBeVisible();
});
test('invalid imports preserve the current project and the public connection gives setup guidance',async({page})=>{
 await sample(page);await page.locator('#project-file').setInputFiles({name:'config.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"tts":{}}')});await expect(page.locator('#notice')).toContainText('output/project.json');await expect(page.locator('#project-title')).toHaveValue('The Description');
 await page.route('**/api/editor-agent/status',r=>r.fulfill({status:404,body:'not found'}));await page.getByRole('button',{name:'Connect your agent'}).click();await expect(page.locator('#connection-help')).toBeVisible();await expect(page.locator('#chat-form')).toBeHidden();
});
test('chat proposals require Apply and refuse to overwrite intervening manual edits',async({page})=>{
 let events=[],seq=0,reply=false,context;
 await page.route('**/api/editor-agent/**',async r=>{const url=new URL(r.request().url()),path=url.pathname;let body={};if(path.endsWith('/status'))body={enabled:true};else if(path.endsWith('/sessions'))body={id:'test-session'};else if(path.endsWith('/messages')){context=r.request().postDataJSON().context;reply=true;}else if(path.endsWith('/events')){if(reply){events.push({id:++seq,type:'text',text:'```json\n{"changes":[{"op":"title","text":"A New Title"}]}\n```'},{id:++seq,type:'done'});reply=false;}body={events:events.filter(e=>e.id>Number(url.searchParams.get('after')))};}await r.fulfill({contentType:'application/json',body:JSON.stringify(body)});});
 await sample(page);await page.getByRole('button',{name:'Connect your agent'}).click();await page.getByLabel('Ask Hermes about this project').fill('Give it a new title');await page.getByRole('button',{name:'Send to Hermes',exact:true}).click();await expect(page.locator('#apply-proposal')).toBeVisible();await expect(page.locator('#project-title')).toHaveValue('The Description');expect(context.title).toBe('The Description');await page.locator('#apply-proposal').click();await expect(page.locator('#project-title')).toHaveValue('A New Title');
 await page.getByLabel('Ask Hermes about this project').fill('Again');await page.getByRole('button',{name:'Send to Hermes',exact:true}).click();await expect(page.locator('#apply-proposal')).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await page.locator('#project-title').fill('My manual title');await page.locator('#project-title').press('Tab');await page.getByRole('button',{name:'Connect your agent'}).click();await page.locator('#apply-proposal').click();await expect(page.locator('#chat-log')).toContainText('Your project changed');await expect(page.locator('#project-title')).toHaveValue('My manual title');
});
