const $=id=>document.getElementById(id);
const storageKey='pelicans.storyboard.prototype.v1';
let board,voices={};
const message=text=>{$('notice').textContent=text;};
const element=(tag,text,className)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;};
function text(value,max=2000){if(typeof value!=='string'||value.length>max)throw Error('Invalid or oversized text field.');return value;}
function number(value,min,max){if(!Number.isFinite(value)||value<min||value>max)throw Error('Number outside the supported range.');return value;}
function validate(data){
 if(data?.kind!=='pelican-storyboard'||data.schemaVersion!==1)throw Error('Open a pelican-storyboard JSON file, not a rendered project.');
 if(!['portrait','landscape'].includes(data.orientation))throw Error('Choose portrait or landscape.');
 if(!Array.isArray(data.cast)||data.cast.length<1||data.cast.length>6||!Array.isArray(data.scenes)||data.scenes.length<1||data.scenes.length>20)throw Error('Use 1–6 characters and 1–20 scenes.');
 const cast=data.cast.map(c=>{if(!/^[a-z][a-z0-9_-]{0,39}$/.test(c.id))throw Error('Invalid character ID.');return {id:c.id,name:text(c.name,160),description:text(c.description),voice:text(c.voice,80),x:number(c.x,10,90)};});
 const ids=new Set(cast.map(c=>c.id));if(ids.size!==cast.length)throw Error('Character IDs must be unique.');
 const scenes=data.scenes.map(s=>{if(!['wide','closeup'].includes(s.shot)||!ids.has(s.focus)||!Array.isArray(s.dialogue)||s.dialogue.length>30)throw Error('Invalid scene or character reference.');return {title:text(s.title,160),setting:text(s.setting),shot:s.shot,focus:s.focus,pauseSeconds:number(s.pauseSeconds,0,10),dialogue:s.dialogue.map(l=>{if(!ids.has(l.who))throw Error('Dialogue refers to a missing character.');return {who:l.who,text:text(l.text,1000)};})};});
 return {schemaVersion:1,kind:'pelican-storyboard',revision:Number.isInteger(data.revision)&&data.revision>0?data.revision:1,status:'draft',title:text(data.title,160),premise:text(data.premise),orientation:data.orientation,targetSeconds:number(data.targetSeconds,5,180),tone:text(data.tone),cast,scenes};
}
function handoff(){const approved=board.status==='approved';return `${approved?'Create this reviewed skit through the normal pelican-theater workflow.':'Help me revise this storyboard. Do not generate artwork, speech, or video yet.'}\nFormat: ${board.orientation} (${board.orientation==='portrait'?'9:16':'16:9'}). This is a planning document, not a player project. ${approved?'Use init to make the project, translate this plan into supported skit actions, and preserve its format, cast, dialogue, and planned pauses. Target length is approximate; allow spoken lines to finish. Ask before materially changing the approved plan. Verify selected voice IDs against the actual speech endpoint and let me hear a short character audition before full synthesis.':'Discuss the story, cast designs, framing, and dialogue with me first.'}\n\n${JSON.stringify(board,null,2)}`;}
function sync(){
 $('review-status').textContent=board.status==='approved'?`Approved revision ${board.revision}. Copy the request or download the plan for your agent.`:`Draft revision ${board.revision}. Review the storyboard before approving.`;
 $('approve').disabled=board.status==='approved';$('handoff').value=handoff();$('format-badge').textContent=board.orientation==='portrait'?'Portrait · 9:16':'Landscape · 16:9';
 try{localStorage.setItem(storageKey,JSON.stringify(board));}catch{message('Browser storage unavailable. Download your storyboard to keep it.');}
}
function changed(){board.revision++;board.status='draft';delete board.approvedAt;sync();previews();}
function field(parent,label,value,change,options={}){
 const wrap=element('label',label),input=document.createElement(options.multiline?'textarea':'input');input.value=value;input.setAttribute('aria-label',label);if(options.multiline)input.rows=options.rows||2;else input.type=options.type||'text';if(input.type!=='number')input.maxLength=options.max||2000;for(const k of ['min','max','step'])if(options[k]!==undefined)input[k]=options[k];
 input.addEventListener('input',()=>{if(input.type==='number'&&!input.validity.valid)return;change(input.type==='number'?Number(input.value):input.value);changed();});wrap.append(input);parent.append(wrap);return input;
}
function select(parent,label,value,entries,change){const wrap=element('label',label),input=document.createElement('select');input.setAttribute('aria-label',label);for(const [id,name] of entries){const option=element('option',name);option.value=id;input.append(option);}input.value=value;input.onchange=()=>{change(input.value);changed();};wrap.append(input);parent.append(wrap);return input;}
function button(parent,label,fn){const b=element('button',label,'secondary');b.type='button';b.onclick=fn;parent.append(b);return b;}
function previews(){document.querySelectorAll('.panel').forEach((panel,i)=>{const s=board.scenes[i];panel.className=`panel ${board.orientation==='landscape'?'landscape':''} ${s.shot==='closeup'?'closeup':''}`;panel.replaceChildren();panel.append(element('div',`${s.title} · ${s.shot==='wide'?'Wide shot':'Close-up'}`,'panel-caption'),element('div',undefined,'floor'));for(const c of board.cast){if(s.shot==='closeup'&&c.id!==s.focus)continue;const actor=element('div',undefined,'actor');actor.style.left=`${c.x}%`;actor.append(element('span',c.name));panel.append(actor);}});}
function render(){
 for(const [id,key]of [['title','title'],['premise','premise'],['tone','tone'],['orientation','orientation'],['duration','targetSeconds']])$(id).value=board[key];
 $('cast').replaceChildren();board.cast.forEach(c=>{const card=element('article',undefined,'cast-card');card.append(element('h3',c.id));field(card,`Character name: ${c.id}`,c.name,v=>c.name=v,{max:160});field(card,`Appearance: ${c.id}`,c.description,v=>c.description=v,{multiline:true});select(card,`Voice: ${c.id}`,c.voice,[['','Choose after audition'],...Object.entries(voices).map(([id,v])=>[id,`${id} — ${v.label}`]),...(!voices[c.voice]&&c.voice?[[c.voice,`${c.voice} (verify availability)`]]:[])],v=>c.voice=v);field(card,`Position from left (%): ${c.id}`,c.x,v=>c.x=v,{type:'number',min:10,max:90,step:1});$('cast').append(card);});
 $('scenes').replaceChildren();board.scenes.forEach((s,i)=>{const scene=element('article',undefined,'scene'),visual=element('div'),panel=element('div',undefined,'panel');panel.setAttribute('aria-label',`Scene ${i+1} blocking preview`);visual.append(panel,element('p','Blocking only. Appearance is described in the cast notes.','panel-note'));const notes=element('div');notes.append(element('h3',`Scene ${i+1}`));field(notes,`Scene ${i+1} title`,s.title,v=>s.title=v,{max:160});field(notes,`Scene ${i+1} setting and action`,s.setting,v=>s.setting=v,{multiline:true,rows:3});select(notes,`Scene ${i+1} shot`,s.shot,[['wide','Wide shot'],['closeup','Close-up']],v=>s.shot=v);select(notes,`Scene ${i+1} focus`,s.focus,board.cast.map(c=>[c.id,c.name]),v=>s.focus=v);
 s.dialogue.forEach((line,j)=>{const row=element('div',undefined,'line');select(row,`Scene ${i+1} line ${j+1} speaker`,line.who,board.cast.map(c=>[c.id,c.name]),v=>line.who=v);field(row,`Scene ${i+1} line ${j+1}`,line.text,v=>line.text=v,{multiline:true,max:1000});button(row,'Remove line',()=>{s.dialogue.splice(j,1);changed();render();}).setAttribute('aria-label',`Remove scene ${i+1} line ${j+1}`);notes.append(row);});
 button(notes,'Add dialogue',()=>{if(s.dialogue.length>=30)return message('Maximum 30 lines per scene.');s.dialogue.push({who:board.cast[0].id,text:''});changed();render();});field(notes,`Scene ${i+1} end pause (seconds)`,s.pauseSeconds,v=>s.pauseSeconds=v,{type:'number',min:0,max:10,step:.1});const actions=element('div',undefined,'scene-tools');button(actions,'Move earlier',()=>{[board.scenes[i-1],board.scenes[i]]=[board.scenes[i],board.scenes[i-1]];changed();render();}).disabled=i===0;button(actions,'Move later',()=>{[board.scenes[i],board.scenes[i+1]]=[board.scenes[i+1],board.scenes[i]];changed();render();}).disabled=i===board.scenes.length-1;button(actions,'Remove scene',()=>{board.scenes.splice(i,1);changed();render();}).disabled=board.scenes.length===1;notes.append(actions);scene.append(visual,notes);$('scenes').append(scene);});previews();sync();
}
for(const [id,key]of [['title','title'],['premise','premise'],['tone','tone'],['orientation','orientation'],['duration','targetSeconds']])$(id).addEventListener('input',()=>{if(!board)return;if(id==='duration'&&!$(id).validity.valid)return;board[key]=id==='duration'?Number($(id).value):$(id).value;changed();});
$('open').onclick=()=>$('file').click();
$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>250000)throw Error('File too large (maximum 250 KB).');const next=validate(JSON.parse(await f.text()));board=next;render();message('Storyboard opened as a draft. Existing approval is not carried across imports.');}catch(e){message(e.message);}finally{$('file').value='';}};
$('download').onclick=()=>{if(!board)return;const url=URL.createObjectURL(new Blob([JSON.stringify(board,null,2)],{type:'application/json'})),a=element('a');a.href=url;a.download='storyboard.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('copy').onclick=async()=>{if(!board)return;try{await navigator.clipboard.writeText(handoff());message('Storyboard request copied. Paste it into your agent chat.');}catch{$('handoff').focus();$('handoff').select();message('Select and copy the handoff text below.');}};
$('approve').onclick=()=>{try{validate(board);if(!board.premise.trim()||!board.title.trim()||board.cast.some(c=>!c.name.trim()||!c.description.trim())||board.scenes.some(s=>!s.setting.trim()||s.dialogue.some(l=>!l.text.trim())))throw Error('Fill in the premise, title, character descriptions, scene actions, and any blank dialogue before approving.');board.status='approved';board.approvedAt=new Date().toISOString();sync();message('This version is approved. No generation has started.');}catch(e){message(e.message);}};
$('add-character').onclick=()=>{if(!board)return;if(board.cast.length>=6)return message('Prototype supports up to six characters.');let n=board.cast.length+1;while(board.cast.some(c=>c.id===`character${n}`))n++;board.cast.push({id:`character${n}`,name:`Character ${n}`,description:'',voice:'',x:50});changed();render();};
$('add-scene').onclick=()=>{if(!board)return;if(board.scenes.length>=20)return message('Prototype supports up to twenty scenes.');board.scenes.push({title:'New scene',setting:'',shot:'wide',focus:board.cast[0].id,pauseSeconds:.5,dialogue:[]});changed();render();};
async function demo(){const r=await fetch('prototypes/portrait-storyboard.json');if(!r.ok)throw Error('Could not load the example.');board=validate(await r.json());render();message('Portrait example loaded. Edits save in this browser.');}
$('demo').onclick=()=>{if(board&&!confirm('Replace this draft with the portrait example? Download your current storyboard first if you want to keep it.'))return;demo().catch(e=>message(e.message));};
try{const r=await fetch('voice-labels.json');if(r.ok)voices=(await r.json()).labels||{};let stored;try{stored=JSON.parse(localStorage.getItem(storageKey)||'null');}catch{}if(stored){board=validate(stored);if(stored.status==='approved'&&typeof stored.approvedAt==='string'){board.status='approved';board.approvedAt=stored.approvedAt;}render();message('Your saved storyboard is open.');}else await demo();}catch(e){message(`Could not open storyboard: ${e.message}. Use Open storyboard JSON or Load portrait example.`);}
