(async()=>{
 const $=id=>document.getElementById(id),key='pelicans.voice-labels.v1';let saved={},catalog;
 const tell=text=>{$('status').textContent=text;};
 try{saved=JSON.parse(localStorage.getItem(key)||'{}');if(!saved||Array.isArray(saved)||typeof saved!=='object')saved={};}catch{saved={};}
 const notes=()=>{const lines=catalog.voices.filter(v=>saved[v.id]?.label||saved[v.id]?.character).map(v=>`${v.id}: ${saved[v.id].label||'No description yet'}${saved[v.id].character?` — cast as ${saved[v.id].character}`:''}`);return `Use Pocket 2.1.0 with the pinned April English preset catalog (voice revision ${catalog.voiceCatalog.revision}). Keep these exact preset IDs when selecting voices. My descriptions are subjective listening notes. Confirm that the speech endpoint offers each selected ID before synthesizing.\n\n${lines.length?lines.join('\n'):'No voices labeled yet. Ask me to audition a couple of voices for the characters.'}\n\nSampler: https://pelicans.art/voices.html\nPlease confirm the character-to-voice assignments and let me hear a short line before rendering the full skit.`;};
 function update(){ $('agent-notes').value=notes();try{localStorage.setItem(key,JSON.stringify(saved));tell('Labels saved in this browser.');}catch{tell('Browser storage is unavailable. Download your labels to keep them.');}}
 try{const r=await fetch('voice-samples.json');if(!r.ok)throw Error();catalog=await r.json();$('sample-text').textContent=`“${catalog.sampleText}”`;
 for(const voice of catalog.voices){const row=document.createElement('article');row.className='voice-row';row.dataset.id=voice.id;const listening=document.createElement('div');listening.className='listening';const title=document.createElement('h2');title.textContent=voice.id;const audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.src=voice.audio;audio.setAttribute('aria-label',`Audition ${voice.id}`);audio.addEventListener('play',()=>document.querySelectorAll('audio').forEach(other=>{if(other!==audio)other.pause();}));audio.addEventListener('error',()=>tell(`Could not load ${voice.id}. Reload the page and try again.`));listening.append(title,audio);const fields=document.createElement('div');fields.className='fields';for(const [field,label,placeholder]of [['label','Your descriptive label','e.g. dry, low-voiced narrator'],['character','Character / role (optional)','e.g. officer']]){const wrapper=document.createElement('label');wrapper.textContent=label;const input=document.createElement('input');input.maxLength=160;input.value=typeof saved[voice.id]?.[field]==='string'?saved[voice.id][field].slice(0,160):'';input.placeholder=placeholder;input.setAttribute('aria-label',`${label}: ${voice.id}`);input.addEventListener('input',()=>{saved[voice.id]={...saved[voice.id],[field]:input.value};update();});wrapper.append(input);fields.append(wrapper);}row.append(listening,fields);$('voices').append(row);}
 $('agent-notes').value=notes();tell(`${catalog.voices.length} voices ready to audition.`);
 $('search').addEventListener('input',()=>{const q=$('search').value.toLowerCase();document.querySelectorAll('.voice-row').forEach(row=>row.hidden=!`${row.dataset.id} ${saved[row.dataset.id]?.label||''} ${saved[row.dataset.id]?.character||''}`.toLowerCase().includes(q));});
 $('copy-voices').onclick=async()=>{try{await navigator.clipboard.writeText(notes());tell('Voice choices copied. Paste them into your agent chat.');}catch{$('agent-notes').focus();$('agent-notes').select();tell('Select and copy the casting notes below.');}};
 $('export-labels').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:1,voiceRevision:catalog.voiceCatalog.revision,labels:saved},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pelican-voice-labels.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('import-labels').onchange=async()=>{try{const file=$('import-labels').files[0];if(!file)return;if(file.size>100000)throw Error('File is too large.');const data=JSON.parse(await file.text());if(data.schemaVersion!==1||data.voiceRevision!==catalog.voiceCatalog.revision||!data.labels)throw Error('This file does not match the current voice catalog.');const accepted={};for(const v of catalog.voices){const entry=data.labels[v.id];if(entry)accepted[v.id]={label:typeof entry.label==='string'?entry.label.slice(0,160):'',character:typeof entry.character==='string'?entry.character.slice(0,160):''};}saved={...saved,...accepted};update();location.reload();}catch(e){tell(`Could not import labels: ${e.message}`);}};
 }catch{tell('Auditions could not load. Reload this page to try again.');}
})();
