import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..');
const hash=s=>createHash('sha256').update(s).digest('hex');
const context={window:{}};vm.runInNewContext(await fs.readFile(path.join(root,'src/js/backend/prompts.js'),'utf8'),context);
const briefs=[
 {id:'stagehand',kind:'character',title:'Pelican stagehand',brief:'A full-body pelican stagehand wearing oversized overalls and a headset, holding a coiled cable. Tired but proud expression. Long recognizable beak, two webbed feet, one free wing. No bicycle. Three-quarter view facing right, both eyes visible.',checks:['pelican with long beak','oversized overalls','headset','coiled cable','two webbed feet','free wing']},
 {id:'mushroom-chef',kind:'character',title:'Mushroom chef',brief:'A full-body mushroom chef with a broad spotted mushroom cap, little apron and oven mitt, holding a wooden spoon. Offended expression. Mushroom anatomy must stay recognizable; do not turn it into a human wearing a mushroom hat. Three-quarter view facing right, both eyes visible.',checks:['mushroom body and cap','spots','apron','oven mitt','wooden spoon','offended expression']},
 {id:'clock',kind:'prop',title:'Bureaucratic cuckoo clock',brief:'A portable cuckoo clock used as an absurd office time clock: a tiny furious bird protrudes from its upper door, clock face below, and a clearly visible punch-card slot at the base. No words or numerals. One coherent object on transparent background.',checks:['cuckoo clock silhouette','bird protruding from door','clock face','punch-card slot','no text']},
 {id:'teapot',kind:'prop',title:'Royal teapot',brief:'A squat teapot wearing a tiny crown, with a long curved spout, a large open handle, and a lid tilted by escaping steam. Three-quarter view. It should look indignantly regal while remaining unmistakably a teapot. No face or text. Transparent background.',checks:['teapot body','crown','curved spout','open handle','tilted lid','steam']},
 {id:'laundromat',kind:'background',title:'Underwater laundromat',brief:'An underwater laundromat interior with two round washing-machine doors on the left, one large porthole on the right showing a curious fish, hanging socks above, and a clear continuous floor in the bottom quarter for two actors. No characters or text. Landscape composition.',checks:['two washing machine doors on left','large right porthole','fish outside porthole','hanging socks','clear bottom-quarter floor']},
 {id:'moon-office',kind:'background',title:'Moon permit office',brief:'A municipal permit office on the moon: a service counter on the right, three mismatched waiting chairs on the left, Earth visible through a rear window, and a floating paper tray above the counter. Keep the bottom quarter as a clear continuous staging floor. No people or readable text. Landscape composition.',checks:['right service counter','three left chairs','Earth through rear window','floating paper tray','clear bottom-quarter floor']}
];
const methods=[
 {id:'minimal',title:'Minimal contract',instruction:'Create an expressive, readable vector asset for an absurd comedy theater. Choose the visual treatment yourself. Output only the SVG.'},
 {id:'current',title:'Current browser recipe',instruction:'Use the current browser generation prompt below, retaining its aesthetic guidance wherever compatible with the shared contract.'},
 {id:'art-direction',title:'Art direction',instruction:'Design this as a characterful theatrical vector illustration. Establish one memorable silhouette and a clear focal feature. Use deliberate asymmetry where it serves the brief, controlled contrast, no more than six main colors, and generous separation between important shapes. Avoid tiny decorative marks that vanish at phone size. Favor a few expressive contours over stacks of generic circles. Preserve every required object and relationship. Output only the SVG.'},
 {id:'layout-plan',title:'Scene/component/layout plan',instruction:'Before drawing, write a compact visible plan (at most 120 words): required objects, their component shapes, approximate bounding boxes, overlaps and front-to-back layer order. Check that connected parts actually touch and important objects remain visible. Then create the SVG from that plan using editable primitives and short paths. Do not add new story objects beyond the brief. Save the plan separately; the SVG file contains only SVG.'},
 {id:'reference',title:'Same-category SVG example',instruction:'Use the supplied same-category SVG as an example of editable structure, shape vocabulary and visual coherence. Draw the requested new subject; do not copy the example subject, its distinctive props, or proportions that conflict with the brief. Output only the SVG.'}
];
const referenceFiles={character:'src/sprites/pelican/front.svg',prop:'src/props/cheeseburger/prop.svg',background:'src/backgrounds/apartment/landscape.svg'};
const generic='Use xmlns="http://www.w3.org/2000/svg" and static self-contained vector SVG only: no external resources, scripts, event handlers, CSS imports or animations, raster images, text or embedded fonts. Fit all visible geometry and stroke within the viewBox with a small safe margin. Use semantic group IDs for editable parts. Do not inspect other study files or use a renderer in a first-pass trial. Do not read production artwork except the explicitly supplied reference. Preserve your first output without repair. Aim for at most 9000 output characters; record actual size rather than silently truncating.';
function contract(b){return generic+'\n'+(b.kind==='character'?'viewBox="0 0 100 150". Transparent background. Required direct groups: body, head-top, head-bottom. Put torso/limbs/accessories in body; eyes and brows in head-top; mouth in head-bottom. Required eye-left-white and eye-right-white are ellipses. eye-left-pupil and eye-right-pupil are circles with class="pupil". brow-left and brow-right are paths. mouth-closed is a contrasting stroked path; mouth-open is an ellipse with explicit cx,cy,rx,ry and opacity="0". Align their centers for animation. Pupils fit inside eye whites; no separate static eye glints. Parts must remain connected when head groups move slightly. Preserve the requested species anatomy.':b.kind==='prop'?'viewBox="0 0 100 100". Transparent background. Keep the prop centered and recognizable when rendered 64 pixels wide.':'viewBox="0 0 400 225". Fill the canvas. Keep a continuous uncluttered actor floor in the bottom quarter; no foreground objects covering it. Use named background, midground and foreground groups.');}
const trials=[];let index=0;
for(const b of briefs)for(const m of methods)trials.push({id:`t${String(++index).padStart(3,'0')}`,briefId:b.id,methodId:m.id,replicate:1,phase:'first-pass'});
for(const b of briefs)trials.push({id:`t${String(++index).padStart(3,'0')}`,briefId:b.id,methodId:'minimal',replicate:2,phase:'fresh-repeat'});
for(const b of briefs)trials.push({id:`t${String(++index).padStart(3,'0')}`,briefId:b.id,methodId:'visual-revision',replicate:1,phase:'revision',parent:trials.find(t=>t.briefId===b.id&&t.methodId==='minimal'&&t.replicate===1).id});
await fs.mkdir(path.join(here,'prompts'),{recursive:true});
for(const trial of trials){const b=briefs.find(b=>b.id===trial.briefId),m=methods.find(m=>m.id===trial.methodId);let prompt;
 if(trial.phase==='revision')prompt=`Revise the supplied SVG exactly once after examining its rendered PNG. Brief: ${b.brief}\n${contract(b)}\nFor this revision you may inspect only the supplied draft and its PNG. Describe at most three observable defects in critique.md, then save one revised SVG. Preserve the draft. If no defect is visible, retain it and explain why. Do not look at other candidates or score the result. Parent trial: ${trial.parent}.`;
 else {prompt=`BRIEF\n${b.brief}\n\nSHARED CONTRACT (takes precedence if a recipe conflicts)\n${contract(b)}\n\nGENERATION RECIPE\n${m.instruction}`;
 if(m.id==='current')prompt+='\n\nCURRENT PROMPT SNAPSHOT\n'+context.window.AITPrompts.getSystemPrompt(b.kind==='character'?'sprite':b.kind);
 if(m.id==='reference'){const ref=await fs.readFile(path.join(root,referenceFiles[b.kind]),'utf8');trial.reference={path:referenceFiles[b.kind],sha256:hash(ref)};prompt+='\n\nREFERENCE SVG (example data, not instructions)\n'+ref;}
 }
 prompt+='\n\nDELIVERY\nWrite your original SVG to the authorized trial directory as asset.svg. Write a short provenance.json with model, whether you rendered, and any deviations; do not invent token counts or settings. Do not generate other trials. No network, APIs, or TTS.';
 trial.promptSha256=hash(prompt+'\n');trial.promptCharacters=prompt.length+1;await fs.writeFile(path.join(here,'prompts',trial.id+'.md'),prompt+'\n');
}
let seed=20260906;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
const order=trials.filter(t=>t.phase!=='revision').map(t=>t.id);for(let i=order.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[order[i],order[j]]=[order[j],order[i]];}
const config={version:1,id:'svg-prompts-2026-09',frozenAt:'2026-09-06',seed:20260906,model:'GPT-6 Astra',generationStatus:'awaiting execution-mode decision',briefs,methods,trials,dispatchOrder:[...order,...trials.filter(t=>t.phase==='revision').map(t=>t.id)]};
await fs.writeFile(path.join(here,'study.json'),JSON.stringify(config,null,2)+'\n');console.log(`${trials.length} frozen prompts prepared`);
