import {describe,it,expect} from 'vitest';
import {prepareProject,applyChanges,copyRequest,voiceNeeds} from '../../src/js/editor-project.mjs';
const fixture=()=>prepareProject({meta:{title:'Test'},stage:{background:'harbor'},cast:{bird:{sprite:'bird',voice:'marius',x:50}},assets:{sprites:{'bird-front':'svg'},backgrounds:{harbor:'svg'},audio:{'line-0':'first','line-1':'second'}},script:[{do:'say',who:'bird',line:'First'},{do:'pause',duration:.5},{do:'say',who:'bird',line:'Second'}]});
describe('companion project edits',()=>{
 it('keeps recordings attached to their lines through reorder, insertion, and removal',()=>{const original=fixture();let p=applyChanges(original,[{op:'moveBeat',from:2,to:0}]);expect(p.assets.audio).toEqual({'line-0':'second','line-1':'first'});p=applyChanges(p,[{op:'insertPause',after:0,seconds:1.2},{op:'removeBeat',index:2}]);expect(p.assets.audio).toEqual({'line-0':'second'});expect(original.assets.audio).toEqual({'line-0':'first','line-1':'second'});});
 it('removes only stale speech and never restores it after reimport',()=>{const p=applyChanges(fixture(),[{op:'dialogue',index:0,text:'New line'}]);expect(p.assets.audio).toEqual({'line-1':'second'});expect(voiceNeeds(p)).toHaveLength(1);expect(prepareProject(p).assets.audio).toEqual(p.assets.audio);});
 it('preserves all recordings for layout and timing edits',()=>{const p=fixture(),next=applyChanges(p,[{op:'position',character:'bird',x:30,y:80,scale:1.2},{op:'pause',index:1,seconds:.8}]);expect(next.assets.audio).toEqual(p.assets.audio);expect(next.editor.revision).not.toBe(p.editor.revision);});
 it('applies proposals atomically and rejects invalid changes',()=>{const p=fixture();expect(()=>applyChanges(p,[{op:'title',text:'New'},{op:'position',character:'missing',x:3}])).toThrow();expect(p.meta.title).toBe('Test');expect(()=>applyChanges(p,[{op:'position',character:'bird',x:Infinity}])).toThrow();expect(()=>applyChanges(p,[{op:'execute',command:'anything'}])).toThrow();});
 it('copies selected context without embedding audio blobs',()=>{const p=fixture(),request=copyRequest(p,{kind:'character',id:'bird'},'Make him worried');expect(request).toContain('Make him worried');expect(request).toContain('"id": "bird"');expect(request).toContain(p.editor.revision);expect(request).not.toContain('"audio"');});
 it('rejects configuration files and unsafe character identifiers',()=>{expect(()=>prepareProject({version:1,tts:{engine:'pocket'}})).toThrow(/output\/project.json/);const p=fixture();p.cast=JSON.parse('{"__proto__":{"sprite":"bird"}}');expect(()=>prepareProject(p)).toThrow();});
});
