const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderSharePage({ title, description, model = 'Unknown', url, playerUrl, image, portrait = false }) {
  const embeddedUrl = new URL(playerUrl);
  embeddedUrl.searchParams.set('controls', 'below');
  embeddedUrl.searchParams.set('layout', 'clean-controls');
  // All URLs are constructed by the caller from known origins and encoded identifiers.
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escape(title)} — pelicans.art</title><meta name="description" content="${escape(description)}">
<link rel="canonical" href="${escape(url)}"><meta property="og:type" content="video.other"><meta property="og:site_name" content="pelicans.art"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(url)}">
${image ? `<meta property="og:image" content="${escape(image)}"><meta property="og:image:alt" content="${escape(title)} — skit preview"><meta name="twitter:card" content="summary_large_image">` : '<meta name="twitter:card" content="summary">'}
<style>*{box-sizing:border-box}body{margin:0;background:#f8f3e8;color:#173a43;font-family:system-ui,sans-serif}main{max-width:1040px;margin:auto;padding:20px}a{color:inherit}header{display:flex;align-items:center;justify-content:space-between;gap:16px}h1{font-size:clamp(24px,5vw,38px);margin:24px 0 8px}p{line-height:1.5}.player-frame{position:relative;width:100%;aspect-ratio:${portrait ? '9/16' : '16/9'};margin-bottom:72px;${portrait ? 'max-width:430px;margin-left:auto;margin-right:auto;' : ''}}iframe{position:absolute;top:0;left:0;display:block;width:100%;height:calc(100% + 56px);border:0;border-radius:12px;background:transparent}button{border:0;border-radius:8px;padding:12px 18px;background:#173a43;color:white;font:inherit;cursor:pointer}#share-status{min-height:24px;font-size:14px}.model{font-size:14px;color:#4c666a}</style>
</head><body><main><header><a href="https://pelicans.art/">pelicans.art</a><button id="share-button">Share skit</button></header><h1>${escape(title)}</h1><p>${escape(description)}</p><div class="player-frame"><iframe title="${escape(title)}" src="${escape(embeddedUrl.href)}" allow="autoplay; fullscreen" allowfullscreen></iframe></div><p class="model">Model: ${escape(model || 'Unknown')}</p><p id="share-status" role="status"></p><a href="https://pelicans.art/community.html?type=published">More skits in the Pouch</a></main><script src="https://pelicans.art/js/share-controls.js"></script></body></html>`;
}
